### PR TITLE
Add model span when printing regarima

### PR DESCRIPTION
**Pull request by TanguyBarthelemy**

### CODE REVIEW

**Comment by AQLT** [comment]
Why do you want to add the model span to the print method?

**Comment by TanguyBarthelemy** [comment]
This information is missing in the current print. But it could be very useful to the user to specify what the span is and remind (if the user has forgotten this information) that there is one.
Why not include this information?

**Comment by AQLT** [comment]
The information is already in the summary print method. The print method is supposed to be "simplified" (even if I think we should remove some statistics to have a very simple output) and the summary provides a more detailed output. Most of the time it will be redundant with the series span of the input time series. Moreover it is not printed in other seasonal adjustment / time series model packages.
So why do you think it is not enough to have it printed in the summary method?

**Comment by TanguyBarthelemy** [comment]
Ok, I'll discuss it with @annasmyk. But I find that it may be a little difficult and twisted to find this information like that (you have to call another function with only the regarima part of your sai (`summary(sai)` doesn't return anything).

**Comment by AQLT** [comment]
So maybe we should implement a `summary.SA()` function which would only run the `summary(object$regarima)`?

**Comment by annasmyk** [comment]
I would be strongly in favor of it appearing in the print as well..

**Pull request closed without merging**
